version: "3.9"

services:
  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=production